// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EasyGrpc.proto

package com.cht.easygrpc;

public final class EasyGrpcProto {
  private EasyGrpcProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EasyGrpcRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EasyGrpcRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EasyGrpcResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EasyGrpcResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016EasyGrpc.proto\"c\n\017EasyGrpcRequest\022\r\n\005r" +
      "eqId\030\001 \001(\t\022\r\n\005rpcId\030\002 \001(\t\022\r\n\005iface\030\003 \001(\t" +
      "\022\016\n\006method\030\004 \001(\t\022\023\n\013requestJson\030\005 \001(\t\"A\n" +
      "\020EasyGrpcResponse\022\014\n\004code\030\001 \001(\005\022\013\n\003msg\030\002" +
      " \001(\t\022\022\n\nresultJson\030\003 \001(\t2y\n\017EasyGrpcServ" +
      "ice\022-\n\004call\022\020.EasyGrpcRequest\032\021.EasyGrpc" +
      "Response\"\000\0227\n\ncallStream\022\020.EasyGrpcReque" +
      "st\032\021.EasyGrpcResponse\"\000(\0010\001B)\n\020com.cht.e" +
      "asygrpcB\rEasyGrpcProtoP\001\242\002\003HLWb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_EasyGrpcRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_EasyGrpcRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EasyGrpcRequest_descriptor,
        new String[] { "ReqId", "RpcId", "Iface", "Method", "RequestJson", });
    internal_static_EasyGrpcResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_EasyGrpcResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EasyGrpcResponse_descriptor,
        new String[] { "Code", "Msg", "ResultJson", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
