// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EasyGrpc.proto

package com.cht.easygrpc;

/**
 * Protobuf type {@code EasyGrpcRequest}
 */
public final class EasyGrpcRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:EasyGrpcRequest)
    EasyGrpcRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use EasyGrpcRequest.newBuilder() to construct.
  private EasyGrpcRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EasyGrpcRequest() {
    reqId_ = "";
    rpcId_ = "";
    iface_ = "";
    method_ = "";
    requestJson_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new EasyGrpcRequest();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private EasyGrpcRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            String s = input.readStringRequireUtf8();

            reqId_ = s;
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            rpcId_ = s;
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            iface_ = s;
            break;
          }
          case 34: {
            String s = input.readStringRequireUtf8();

            method_ = s;
            break;
          }
          case 42: {
            String s = input.readStringRequireUtf8();

            requestJson_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return EasyGrpcProto.internal_static_EasyGrpcRequest_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return EasyGrpcProto.internal_static_EasyGrpcRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            EasyGrpcRequest.class, Builder.class);
  }

  public static final int REQID_FIELD_NUMBER = 1;
  private volatile Object reqId_;
  /**
   * <code>string reqId = 1;</code>
   * @return The reqId.
   */
  @Override
  public String getReqId() {
    Object ref = reqId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      reqId_ = s;
      return s;
    }
  }
  /**
   * <code>string reqId = 1;</code>
   * @return The bytes for reqId.
   */
  @Override
  public com.google.protobuf.ByteString
      getReqIdBytes() {
    Object ref = reqId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      reqId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RPCID_FIELD_NUMBER = 2;
  private volatile Object rpcId_;
  /**
   * <code>string rpcId = 2;</code>
   * @return The rpcId.
   */
  @Override
  public String getRpcId() {
    Object ref = rpcId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      rpcId_ = s;
      return s;
    }
  }
  /**
   * <code>string rpcId = 2;</code>
   * @return The bytes for rpcId.
   */
  @Override
  public com.google.protobuf.ByteString
      getRpcIdBytes() {
    Object ref = rpcId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      rpcId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IFACE_FIELD_NUMBER = 3;
  private volatile Object iface_;
  /**
   * <code>string iface = 3;</code>
   * @return The iface.
   */
  @Override
  public String getIface() {
    Object ref = iface_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      iface_ = s;
      return s;
    }
  }
  /**
   * <code>string iface = 3;</code>
   * @return The bytes for iface.
   */
  @Override
  public com.google.protobuf.ByteString
      getIfaceBytes() {
    Object ref = iface_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      iface_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int METHOD_FIELD_NUMBER = 4;
  private volatile Object method_;
  /**
   * <code>string method = 4;</code>
   * @return The method.
   */
  @Override
  public String getMethod() {
    Object ref = method_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      method_ = s;
      return s;
    }
  }
  /**
   * <code>string method = 4;</code>
   * @return The bytes for method.
   */
  @Override
  public com.google.protobuf.ByteString
      getMethodBytes() {
    Object ref = method_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      method_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REQUESTJSON_FIELD_NUMBER = 5;
  private volatile Object requestJson_;
  /**
   * <code>string requestJson = 5;</code>
   * @return The requestJson.
   */
  @Override
  public String getRequestJson() {
    Object ref = requestJson_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      requestJson_ = s;
      return s;
    }
  }
  /**
   * <code>string requestJson = 5;</code>
   * @return The bytes for requestJson.
   */
  @Override
  public com.google.protobuf.ByteString
      getRequestJsonBytes() {
    Object ref = requestJson_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      requestJson_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getReqIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, reqId_);
    }
    if (!getRpcIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, rpcId_);
    }
    if (!getIfaceBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, iface_);
    }
    if (!getMethodBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, method_);
    }
    if (!getRequestJsonBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, requestJson_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getReqIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, reqId_);
    }
    if (!getRpcIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, rpcId_);
    }
    if (!getIfaceBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, iface_);
    }
    if (!getMethodBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, method_);
    }
    if (!getRequestJsonBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, requestJson_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof EasyGrpcRequest)) {
      return super.equals(obj);
    }
    EasyGrpcRequest other = (EasyGrpcRequest) obj;

    if (!getReqId()
        .equals(other.getReqId())) return false;
    if (!getRpcId()
        .equals(other.getRpcId())) return false;
    if (!getIface()
        .equals(other.getIface())) return false;
    if (!getMethod()
        .equals(other.getMethod())) return false;
    if (!getRequestJson()
        .equals(other.getRequestJson())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + REQID_FIELD_NUMBER;
    hash = (53 * hash) + getReqId().hashCode();
    hash = (37 * hash) + RPCID_FIELD_NUMBER;
    hash = (53 * hash) + getRpcId().hashCode();
    hash = (37 * hash) + IFACE_FIELD_NUMBER;
    hash = (53 * hash) + getIface().hashCode();
    hash = (37 * hash) + METHOD_FIELD_NUMBER;
    hash = (53 * hash) + getMethod().hashCode();
    hash = (37 * hash) + REQUESTJSON_FIELD_NUMBER;
    hash = (53 * hash) + getRequestJson().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static EasyGrpcRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static EasyGrpcRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static EasyGrpcRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static EasyGrpcRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static EasyGrpcRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static EasyGrpcRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static EasyGrpcRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static EasyGrpcRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static EasyGrpcRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static EasyGrpcRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static EasyGrpcRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static EasyGrpcRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(EasyGrpcRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code EasyGrpcRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:EasyGrpcRequest)
      EasyGrpcRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return EasyGrpcProto.internal_static_EasyGrpcRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return EasyGrpcProto.internal_static_EasyGrpcRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              EasyGrpcRequest.class, Builder.class);
    }

    // Construct using com.cht.easygrpc.EasyGrpcRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      reqId_ = "";

      rpcId_ = "";

      iface_ = "";

      method_ = "";

      requestJson_ = "";

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return EasyGrpcProto.internal_static_EasyGrpcRequest_descriptor;
    }

    @Override
    public EasyGrpcRequest getDefaultInstanceForType() {
      return EasyGrpcRequest.getDefaultInstance();
    }

    @Override
    public EasyGrpcRequest build() {
      EasyGrpcRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public EasyGrpcRequest buildPartial() {
      EasyGrpcRequest result = new EasyGrpcRequest(this);
      result.reqId_ = reqId_;
      result.rpcId_ = rpcId_;
      result.iface_ = iface_;
      result.method_ = method_;
      result.requestJson_ = requestJson_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof EasyGrpcRequest) {
        return mergeFrom((EasyGrpcRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(EasyGrpcRequest other) {
      if (other == EasyGrpcRequest.getDefaultInstance()) return this;
      if (!other.getReqId().isEmpty()) {
        reqId_ = other.reqId_;
        onChanged();
      }
      if (!other.getRpcId().isEmpty()) {
        rpcId_ = other.rpcId_;
        onChanged();
      }
      if (!other.getIface().isEmpty()) {
        iface_ = other.iface_;
        onChanged();
      }
      if (!other.getMethod().isEmpty()) {
        method_ = other.method_;
        onChanged();
      }
      if (!other.getRequestJson().isEmpty()) {
        requestJson_ = other.requestJson_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      EasyGrpcRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (EasyGrpcRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object reqId_ = "";
    /**
     * <code>string reqId = 1;</code>
     * @return The reqId.
     */
    public String getReqId() {
      Object ref = reqId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        reqId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string reqId = 1;</code>
     * @return The bytes for reqId.
     */
    public com.google.protobuf.ByteString
        getReqIdBytes() {
      Object ref = reqId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        reqId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string reqId = 1;</code>
     * @param value The reqId to set.
     * @return This builder for chaining.
     */
    public Builder setReqId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      reqId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string reqId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearReqId() {
      
      reqId_ = getDefaultInstance().getReqId();
      onChanged();
      return this;
    }
    /**
     * <code>string reqId = 1;</code>
     * @param value The bytes for reqId to set.
     * @return This builder for chaining.
     */
    public Builder setReqIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      reqId_ = value;
      onChanged();
      return this;
    }

    private Object rpcId_ = "";
    /**
     * <code>string rpcId = 2;</code>
     * @return The rpcId.
     */
    public String getRpcId() {
      Object ref = rpcId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        rpcId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string rpcId = 2;</code>
     * @return The bytes for rpcId.
     */
    public com.google.protobuf.ByteString
        getRpcIdBytes() {
      Object ref = rpcId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        rpcId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string rpcId = 2;</code>
     * @param value The rpcId to set.
     * @return This builder for chaining.
     */
    public Builder setRpcId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      rpcId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string rpcId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearRpcId() {
      
      rpcId_ = getDefaultInstance().getRpcId();
      onChanged();
      return this;
    }
    /**
     * <code>string rpcId = 2;</code>
     * @param value The bytes for rpcId to set.
     * @return This builder for chaining.
     */
    public Builder setRpcIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      rpcId_ = value;
      onChanged();
      return this;
    }

    private Object iface_ = "";
    /**
     * <code>string iface = 3;</code>
     * @return The iface.
     */
    public String getIface() {
      Object ref = iface_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        iface_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string iface = 3;</code>
     * @return The bytes for iface.
     */
    public com.google.protobuf.ByteString
        getIfaceBytes() {
      Object ref = iface_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        iface_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string iface = 3;</code>
     * @param value The iface to set.
     * @return This builder for chaining.
     */
    public Builder setIface(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      iface_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string iface = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearIface() {
      
      iface_ = getDefaultInstance().getIface();
      onChanged();
      return this;
    }
    /**
     * <code>string iface = 3;</code>
     * @param value The bytes for iface to set.
     * @return This builder for chaining.
     */
    public Builder setIfaceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      iface_ = value;
      onChanged();
      return this;
    }

    private Object method_ = "";
    /**
     * <code>string method = 4;</code>
     * @return The method.
     */
    public String getMethod() {
      Object ref = method_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        method_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string method = 4;</code>
     * @return The bytes for method.
     */
    public com.google.protobuf.ByteString
        getMethodBytes() {
      Object ref = method_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        method_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string method = 4;</code>
     * @param value The method to set.
     * @return This builder for chaining.
     */
    public Builder setMethod(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      method_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string method = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearMethod() {
      
      method_ = getDefaultInstance().getMethod();
      onChanged();
      return this;
    }
    /**
     * <code>string method = 4;</code>
     * @param value The bytes for method to set.
     * @return This builder for chaining.
     */
    public Builder setMethodBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      method_ = value;
      onChanged();
      return this;
    }

    private Object requestJson_ = "";
    /**
     * <code>string requestJson = 5;</code>
     * @return The requestJson.
     */
    public String getRequestJson() {
      Object ref = requestJson_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        requestJson_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string requestJson = 5;</code>
     * @return The bytes for requestJson.
     */
    public com.google.protobuf.ByteString
        getRequestJsonBytes() {
      Object ref = requestJson_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        requestJson_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string requestJson = 5;</code>
     * @param value The requestJson to set.
     * @return This builder for chaining.
     */
    public Builder setRequestJson(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      requestJson_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string requestJson = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearRequestJson() {
      
      requestJson_ = getDefaultInstance().getRequestJson();
      onChanged();
      return this;
    }
    /**
     * <code>string requestJson = 5;</code>
     * @param value The bytes for requestJson to set.
     * @return This builder for chaining.
     */
    public Builder setRequestJsonBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      requestJson_ = value;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:EasyGrpcRequest)
  }

  // @@protoc_insertion_point(class_scope:EasyGrpcRequest)
  private static final EasyGrpcRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new EasyGrpcRequest();
  }

  public static EasyGrpcRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EasyGrpcRequest>
      PARSER = new com.google.protobuf.AbstractParser<EasyGrpcRequest>() {
    @Override
    public EasyGrpcRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new EasyGrpcRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<EasyGrpcRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<EasyGrpcRequest> getParserForType() {
    return PARSER;
  }

  @Override
  public EasyGrpcRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

