// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EasyGrpc.proto

package com.cht.easygrpc;

public interface EasyGrpcRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EasyGrpcRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string reqId = 1;</code>
   * @return The reqId.
   */
  String getReqId();
  /**
   * <code>string reqId = 1;</code>
   * @return The bytes for reqId.
   */
  com.google.protobuf.ByteString
      getReqIdBytes();

  /**
   * <code>string rpcId = 2;</code>
   * @return The rpcId.
   */
  String getRpcId();
  /**
   * <code>string rpcId = 2;</code>
   * @return The bytes for rpcId.
   */
  com.google.protobuf.ByteString
      getRpcIdBytes();

  /**
   * <code>string iface = 3;</code>
   * @return The iface.
   */
  String getIface();
  /**
   * <code>string iface = 3;</code>
   * @return The bytes for iface.
   */
  com.google.protobuf.ByteString
      getIfaceBytes();

  /**
   * <code>string method = 4;</code>
   * @return The method.
   */
  String getMethod();
  /**
   * <code>string method = 4;</code>
   * @return The bytes for method.
   */
  com.google.protobuf.ByteString
      getMethodBytes();

  /**
   * <code>string requestJson = 5;</code>
   * @return The requestJson.
   */
  String getRequestJson();
  /**
   * <code>string requestJson = 5;</code>
   * @return The bytes for requestJson.
   */
  com.google.protobuf.ByteString
      getRequestJsonBytes();
}
